name: auto PDF generate

on:
  push:
    branches:
      - master  

jobs:
  nodejob:
    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install
        run: npm install

      - name: Generate PDF
        run: npm run generate

      - name: Git commit and push
        run: git add README.pdf && git commit -m 'generate PDF' && git push ${REPO} --all
